services:
  server:
    build: ./server
    command: npm run dev
    restart: always
    env_file: .env
    volumes:
      - ./server:/app/
      - ./persist/public/images:/app/public/images
      - /app/node_modules

  client:
    build: ./client
    command: npm run dev
    restart: always
    volumes:
      - ./client:/app/
      - /app/node_modules

  gateway:
    image: nginx
    ports:
      - 3000:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - server
      - client
